FROM node:18-alpine

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

# serve the static build with a simple server
RUN npm install -g serve

ENV PORT=${PORT:-3000}
CMD ["serve", "-s", "build", "-l", "3000"]
